name: govet_doctor_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # firebase dependencies
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  firebase_auth: ^1.1.1
  #bottom navigation bar
  flutter_snake_navigationbar: ^0.5.0
  #page transition
  page_transition:
  # providers state management
  provider: ^5.0.0
  # progress loading
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: custom_font
    fonts:
      - asset: font/custom_font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  - family: custom_font_bold
    fonts:
      - asset: font/Signika-Bold.ttf
        #- asset: fonts/TrajanPro_Bold.ttf
        weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
